# Generated by Django 2.1.7 on 2019-03-06 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='user',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
